spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.qrirdonddqsfjdpdzwla
    password: sos159630!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  


# spring:
#   datasource:
#     url: jdbc:sqlite:database.db
#     driver-class-name: org.sqlite.JDBC
#     username: root
#     password: 123456
#   data:
#     jdbc:
#       repositories:
#         enabled: true
#   jpa:
#     database-platform: org.hibernate.community.dialect.SQLiteDialect
#   devtools:
#     restart:
#       enabled: true
#     livereload:
#       enabled: true
#   sql:
#     init:
#       mode: always
#       schema-locations: classpath:schema.sql

# logging:
#   level:
#     org.springframework.jdbc.core: TRACE
#     org.springframework.jdbc.core.JdbcTemplate: DEBUG
#     org.springframework.jdbc.core.StatementCreatorUtils: TRACE
